# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  # Removed Papers menu item (content available elsewhere)
  # - name: Talks
  #   url: /#talks
  #   weight: 12
  # Removed News menu item (Recent News shown on homepage)

  - name: Experience
    url: /experience/
    weight: 20
  - name: Research Projects
    url: /projects/
    weight: 30
  # - name: Teaching
  #   url: /teaching/
  #   weight: 40


  - name: CV
    url: /uploads/muhammad_adil_cv.pdf
    weight: 50
  - name: Scholar
    url: https://scholar.google.com/citations?user=SyKq5A4AAAAJ&hl=en
    weight: 60
    params:
      external: true
